apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-vyhpkwjt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-vyhpkwjt 
  name: go-vyhpkwjt
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-vyhpkwjt
    weight: 100 
